Feature/wishlist
BitBagCommerce/SyliusVueStorefront2Plugin pull request #59
Opened 2023-01-25 08:28 UTC by Wojdylak

2023-01-25 13:29 UTC, senghe requested changes

2023-01-25 13:29 UTC, senghe commented on src/CommandHandler/Wishlist/AddItemToWishlistHandler.php
> +    private IriConverterInterface $iriConverter;
```suggestion
    private WishlistRepositoryInterface $wishlistRepository;
    
    private WishlistProductFactoryInterface $wishlistProductFactory;
    
    private IriConverterInterface $iriConverter;
```

2023-01-25 13:29 UTC, senghe commented on src/CommandHandler/Wishlist/CreateNewWishlistHandler.php
> +
```suggestion

```

2023-01-25 13:29 UTC, senghe commented on src/CommandHandler/Wishlist/RemoveItemFromWishlistHandler.php
> +    private IriConverterInterface $iriConverter;
```suggestion
    private ObjectManager $wishlistManager;
    
    private IriConverterInterface $iriConverter;
```

2023-01-25 13:29 UTC, senghe commented on src/CommandHandler/Wishlist/RemoveItemFromWishlistHandler.php
> +
```suggestion

```

2023-01-25 13:29 UTC, senghe commented on src/Doctrine/Orm/Extension/WishlistsCurrentUserExtension.php
> +    const WISHLIST_COLLECTION_OPERATION_NAME = 'shop_get_wishlists';
```suggestion
    const GRAPHQL_OPERATION_KEY = 'graphql_operation_name';
    
    const COLLECTION_OPERATION_KEY = 'collection_operation_name';
    
    const WISHLIST_GRAPHQL_OPERATION_NAME = 'collection_query';
    
    const WISHLIST_COLLECTION_OPERATION_NAME = 'shop_get_wishlists';
```

2023-01-25 13:29 UTC, senghe commented on src/Resources/api_resources/ChannelPricing.xml
> +                    <attribute>bit_bag.sylius_vue_storefront2plugin.filter.channel_pricing_channel_code_filter</attribute>
```suggestion
                    <attribute>bitbag.sylius_vue_storefront2plugin.filter.channel_pricing_channel_code_filter</attribute>
```

2023-01-25 13:29 UTC, senghe commented on src/Resources/api_resources/ChannelPricing.xml
> +            <attribute>bit_bag.sylius_vue_storefront2plugin.filter.channel_pricing_channel_code_filter</attribute>
```suggestion
            <attribute>bitbag.sylius_vue_storefront2plugin.filter.channel_pricing_channel_code_filter</attribute>
```

2023-01-25 13:29 UTC, senghe commented on src/Resources/services/command_handlers.xml
> +            id="bit_bag.sylius_vue_storefront2plugin.command_handler.wishlist.create_new_wishlist_handler"
Could you keep service ids consistent?

2023-01-25 13:29 UTC, senghe commented on src/Validator/UniqueNameShopUserWishlistValidator.php
> +    private WishlistNameCheckerInterface $wishlistNameChecker;
```suggestion
    private Security $security;
    
    private WishlistRepositoryInterface $wishlistRepository;
    
    private WishlistNameCheckerInterface $wishlistNameChecker;
```

2023-01-25 13:29 UTC, senghe commented on tests/Application/config/packages/validator.yaml
> +                - '%kernel.project_dir%/../../src/Resources/validation/'
This information has to be put into installation docs

2023-01-25 13:29 UTC, senghe commented on tests/Application/config/bundles.php
> +    BitBag\SyliusWishlistPlugin\BitBagSyliusWishlistPlugin::class => ['all' => true],
This information has to be put into installation docs

2023-01-25 13:56 UTC, Wojdylak commented on src/Resources/services/command_handlers.xml
> +            id="bit_bag.sylius_vue_storefront2plugin.command_handler.wishlist.create_new_wishlist_handler"
Yes :)

2023-01-26 10:12 UTC, senghe approved these changes

2023-01-26 10:12 UTC, merged