Feature/wishlist tests
BitBagCommerce/SyliusVueStorefront2Plugin pull request #63
Opened 2023-02-01 07:07 UTC by Wojdylak

2023-02-16 11:39 UTC, senghe requested changes

2023-02-16 11:39 UTC, senghe commented on spec/CommandHandler/Cart/AddItemsToCartHandlerSpec.php
> +final class AddItemsToCartHandlerSpec extends ObjectBehavior
At least one missing scenario :vulcan_salute:

2023-02-16 11:39 UTC, senghe commented on src/Doctrine/Orm/Extension/WishlistsCurrentUserExtension.php
> +        $queryBuilder->andWhere(
I would use PHPUnit integration tests nor PHPSpec ones

2023-02-16 11:39 UTC, senghe commented on src/Doctrine/Orm/Extension/WishlistsCurrentUserExtension.php
> +        $queryBuilder->andWhere(
lchrusciel/api-test-case

2023-02-20 12:51 UTC, senghe requested changes

2023-02-20 12:51 UTC, senghe commented on features/shop/cart/adding_products_to_cart.feature
> +    Scenario: Placing order as quest
```suggestion
    Scenario: Placing order as guest
```

2023-02-20 12:51 UTC, senghe commented on features/shop/cart/adding_products_to_cart.feature
> +        And I create a JWT Token for customer identified by an email "aondra@climb.com"
And I am authorized as "aondra@climb.com"

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/clearing_wishlist.feature
> +        Given user have a product "ROPE" in my wishlist "For me"
user has

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/clearing_wishlist.feature
> +        Given user have a product "ROPE" in my wishlist "For me"
You have the literal issue in a few places. Could you localize them and fix also?

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/clearing_wishlist.feature
> +    Scenario: Cleaning a wishlist
Cleaning an empty wishlist ?

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/creating_wishlist.feature
> +        And I create a JWT Token for customer identified by an email "aondra@climb.com"
I authorize as "aondra@climb.com"

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/adding_product_to_wishlist.feature
> +            | wishlist.wishlistProducts.edges.0.node.variant.name   | Harness climbing  | string    |
I think the response tables you can change to sentences i.e.: "And the total count of products is 1", "And the first variant in wishlist is Harness climbing".

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/removing_product_from_wishlist.feature
> +Feature: Adding a product to a wishlist
Removing product from wishlist

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/removing_wishlist.feature
> +    Scenario: Removing wishlists
Duplicated scenario name

2023-02-20 12:51 UTC, senghe commented on features/shop/wishlist/customer/removing_wishlist.feature
> +    Scenario: Removing wishlists
How about removing wishlist having products inside?

2023-02-20 12:51 UTC, senghe commented on tests/Behat/Resources/suites/cart/place_order_as_customer.yaml
> +                tags: "@place_order_customer &@graphql"
possible issue

2023-02-20 12:51 UTC, senghe commented on tests/Integration/Doctrine/WishlistsCurrentUserExtensionTest.php
> +        $productVariantCurrentVendorExtension = new WishlistsCurrentUserExtension($security);
You can get the service directly from container

2023-02-20 14:34 UTC, Wojdylak commented on features/shop/wishlist/customer/removing_wishlist.feature
> +    Scenario: Removing wishlists
I added

2023-02-23 11:07 UTC, senghe commented on tests/Behat/Context/GraphqlApiPlatformContext.php
> +
```suggestion
```

2023-02-23 11:19 UTC, senghe approved these changes

2023-02-23 11:19 UTC, merged